### ISSUE TITLE
directory mtime optimization

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#101]
When running index against an existing database does duc compare the current mtime of directories in the filesystem versus the database to see whether readdir() is needed to update the database, or as a performance optimization whether an update of that directory can be skipped?

**Comment by zevv** [comment]
* On 2015-06-04 01:53:28 +0200, stuartthebruce wrote:
 
> When running index against an existing database does duc compare the
> current mtime of directories in the filesystem versus the database to
> see whether readdir() is needed to update the database, or as a
> performance optimization whether an update of that directory can be
> skipped?

Not yet; I've been experimenting with this some time ago, and it is
indeed possible to get a fair amount of optimization. Simply skipping a
directory if the mtime has not change is not going to work, because duc
will mis any subdirectories which might have changes; it is only safe to
ignore directories by mtime when they hold only files, not
subdirectories.

I'll leave this ticket open as a reminder to look into this once more.
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On Jun 4, 2015, at 12:18 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-06-04 01:53:28 +0200, stuartthebruce wrote:
> 
> > When running index against an existing database does duc compare the
> > current mtime of directories in the filesystem versus the database to
> > see whether readdir() is needed to update the database, or as a
> > performance optimization whether an update of that directory can be
> > skipped?
> 
> Not yet; I've been experimenting with this some time ago, and it is
> indeed possible to get a fair amount of optimization. Simply skipping a
> directory if the mtime has not change is not going to work, because duc
> will mis any subdirectories which might have changes; it is only safe to
> ignore directories by mtime when they hold only files, not
> subdirectories.

Agreed, you can avoid updating the contents of “.” but still need to check
on sub-directories if present.

Since I believe duc is already calling stat() for every file I suspect this
does not apply, but another optimization to consider is if you assume duc
is operating on filesystems that increase the link count on directories
whenever a sub-directory is added then checking for a link count of 2 for
“.” is significant.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
* On 2015-06-04 18:34:22 +0200, stuartthebruce wrote:
 
> Agreed, you can avoid updating the contents of “.” but still need to check
> on sub-directories if present.

The good thing is that if the mtime of a directory has not changed, duc
would not have to opendir()/readdir() the directory and stat() all the
entries at all, since all the info is already available in the duc db.

I guess it would really pay to work on this. This does not fit simply
into the current code I'm afraid, so I'll have to do some refactoring to
get the proper data structures available at the right place. The
administration will get more complicated, but I think the speedup would
be significant.

> Since I believe duc is already calling stat() for every file I suspect this
> does not apply, but another optimization to consider is if you assume duc
> is operating on filesystems that increase the link count on directories
> whenever a sub-directory is added then checking for a link count of 2 for
> “.” is significant.

I've looked into this, but I'm not sure how to realiably detect if a
given file system behaves like this. I'll keep this in mind though,
because it might make for another optimization.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
I've put up a branch called cached-indexing which should do what the branch name implies: if a directory was indexed earlier, and the mtime on the filesystem is the same as before, Duc will not scan this directory from the filesystem but use the cached data instead.

Initial test results for me on a RAID0 system, ubuntu, 7200 RPM disks look promising:

Scan with OS caches flushed, so all data is read from disk speedup x2.25

- first scan: 174 seconds
- cached scan: 77 seconds

Scan with most of the inodes in OS cache speedup x72.5

- first scan: 87 seconds
- cached scan: 1.2 seconds

The current code has not been tested properly; it runs in the happy path but error handling needs some more work. I'm not really fond of the extra complexity added to the code, but I think the considerable speedup will be worth the extra hassle in the end.

**Comment by zevv** [comment]
Closing this ticket for now. The request has been added to `TODO.md`
