### ISSUE TITLE
duc-1.3.1 tar file is missing graph-private.h

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#105]
On an SL6 machine,
# wget https://github.com/zevv/duc/releases/download/1.3.1/duc-1.3.1.tar.gz
# tar xzvf duc-1.3.1.tar.gz 
# cd duc-1.3.1
# ./configure
# make
...
	gcc -DHAVE_CONFIG_H -I.    -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -Isrc/libduc -Isrc/libduc-graph -g -O2 -MT src/libduc-graph/graph.o -MD -MP -MF $depbase.Tpo -c -o src/libduc-graph/graph.o src/libduc-graph/graph.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/libduc-graph/graph.c:22:27: error: graph-private.h: No such file or directory
src/libduc-graph/graph.c: In function ‘duc_graph_new’:
src/libduc-graph/graph.c:35: error: dereferencing pointer to incomplete type
src/libduc-graph/graph.c:36: error: dereferencing pointer to incomplete type

**Comment by zevv** [comment]
Yeah, that's my punishment for a quick bug fix update. I really should formalize my release testing procedure I guess.

1.3.2 coming up, it's a good thing I introduced a 3d digit in the version number, so I have more room for buggy releases :)

**Comment by zevv** [comment]
1.3.2 is there. I'm not sure how to handle releases yet. I feel that for some users it lowers the bar a bit to simply have a .tgz to download instead of doing the git magic, but it adds more hassle to decide when a version is Good Enough to release. 

Making a release means work, so I'll at least have to make some kind of automated unit test to make this easier and less error-prone.
