### ISSUE TITLE
proposal: index only given fs types

### ISSUE THREAD

**Issue by zevv** [zevv/duc#126]
By default duc indexes all directories it encounters, independent of file system type. It is possible to exclude certain directories by path name, but wouldn't it be useful to tell duc what file system types it is allowed to index so that all local file systems are indexed, but things like proc, sysfs and nfs are skipped? The default set might be something like ext2,ext3,ext4,reiserfs,hfs,zfs.

The biggest issue for implementing this would probably be portability, afaik there is no single posixy way of getting this info.

**Comment by stuartthebruce** [comment]
> On Mar 3, 2016, at 6:51 AM, Ico Doornekamp <notifications@github.com> wrote:
> 
> By default duc indexes all directories it encounters, independent of file system type. It is possible to exclude certain directories by path name, but wouldn't it be useful to tell duc what file system types it is allowed to index so that all local file systems are indexed, but things like proc, sysfs and nfs are skipped? The default set might be something like ext2,ext3,ext4,reiserfs,hfs,zfs.
> 
> The biggest issue for implementing this would probably be portability, afaik there is no single posixy way of getting this info.
> 
> 
I think you could get a long ways by parsing the output of mount with no arguments (or looking in /etc/mtab or /etc/mnttab). I think the parsing heuristics for that would be pretty straight forward. It is indeed unfortunate that f_fsid in statvfs is not well defined.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by l8gravely** [comment]
>>>>> "stuartthebruce" == stuartthebruce  <notifications@github.com> writes:

>> On Mar 3, 2016, at 6:51 AM, Ico Doornekamp <notifications@github.com> wrote:
>> 
>> By default duc indexes all directories it encounters, independent of file system type. It is
stuartthebruce> possible to exclude certain directories by path name, but wouldn't it be useful to tell duc what
stuartthebruce> file system types it is allowed to index so that all local file systems are indexed, but things
stuartthebruce> like proc, sysfs and nfs are skipped? The default set might be something like
stuartthebruce> ext2,ext3,ext4,reiserfs,hfs,zfs.
>> 
>> The biggest issue for implementing this would probably be portability, afaik there is no single
stuartthebruce> posixy way of getting this info.
>> 
>> 

stuartthebruce> I think you could get a long ways by parsing the
stuartthebruce> output of mount with no arguments (or looking in
stuartthebruce> /etc/mtab or /etc/mnttab). I think the parsing
stuartthebruce> heuristics for that would be pretty straight
stuartthebruce> forward. It is indeed unfortunate that f_fsid in
stuartthebruce> statvfs is not well defined.

The problem is that the output of mount is even less well defined!  It
might well be better to have a lookup table of OS->filesystem(s) to
map statvfs numbers properly.  I suspect that different versions of
Linux have different outputs as well.

And since this feature needs to be deployed in the data gathering part
of duc, not in the display side, it's going to be exercised across a
larger number of OS versions and filesystems.

John

**Comment by zevv** [comment]
Feeling brave today, I just implemented this functionality to duc index (0de86d8). Two new options have been added to choose which file system types to include or exclude. If neither of these options are given, all file system types are scanned, as was the old default behaviour.

The contents of /proc/mounts and /etc/mtab is used to determine which file system types are mounted on what mount points. As soon as duc notices a directory has a different st_dev then its parent directory, it will try to find the current path in the list of mountpoints, and check if the path is in the --fs-include and/or --fs-exclude list.

It would be nice if people running non-linux OS's could give this feature a try to see if the mechanism is working on these environments as well.

Aloha: potje?
