### ISSUE TITLE
Feature req: Support counting files/per dir?

### ISSUE THREAD

**Issue by l8gravely** [zevv/duc#13]
One possible feature would be to also count the number of files per directory and offer the ability to report on file counts and generate graphs showing that data as well.  Honestly haven't looked into the code to see if that data is counted already or not.  This would be analgous to the 'df -i' output to show number of inodes in a filesystem.

**Comment by bricewge** [comment]
I can't understand why this issued is closed and marked as completed. I can't find reference of such feature in the doc nor the codebase.

Does it fall in "won't implement"? If not, could this issue be reopened?

As a system administrator, having the ability in DUC to find which directory is using most of the inode of a file system, would really be useful. Because we wouldn't to go through the whole file system to get this information.

**Comment by zevv** [comment]
Check out `duc ls --count`, or press the `c` key in `duc ui` or `duc gui`
