### ISSUE TITLE
Requested path not found on OS X for DB created on Solaris but works on Linux

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#130]
With a 64-bit version 1.4.0 using tokyocabinet I am able to generate a database that can be read on Linux (SL6), however,  while the info command can parse the database on OS X (10.11.3), e.g.,

> ~/git/duc/duc-1.4.0/duc info -d zfs2.duc /zfs2
> Date       Time       Files    Dirs    Size Path
> 2016-03-05 00:30:10    1.7M   15.8K   21.9T /zfs2

an attempt to "ls" fails on OS X,

> ~/git/duc/duc-1.4.0/duc ls -d zfs2.duc /zfs2
> Requested path not found

**Comment by zevv** [comment]
* On 2016-03-05 20:46:03 +0100, stuartthebruce wrote:
 
> With a 64-bit version 1.4.0 using tokyocabinet I am able to generate a
> database that can be read on Linux (SL6), however,  while the info
> command can parse the database on OS X (10.11.3), e.g.,
> 
> > ~/git/duc/duc-1.4.0/duc info -d zfs2.duc /zfs2
> Date       Time       Files    Dirs    Size Path
> 2016-03-05 00:30:10    1.7M   15.8K   21.9T /zfs2
> 
> an attempt to "ls" fails on OS X,
> 
> > ~/git/duc/duc-1.4.0/duc ls -d zfs2.duc /zfs2
> Requested path not found

Tokyocabinet files are not portable over operating systems or
architecture, and unfortunately will never be. If you want your
databases to be usuable on more then one system type, use the sqlite
backend.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
Understood. However, I am able to create tokyocabinet files with a Solaris 64-bit version of duc on x86_64 and read them correctly on Linux x86_64. It would be nice to be able to read them on my OSX x864_64 laptop.

To avoid the significantly larger file size created by sqlite3 have you considered adding compression, e.g., http://www.hwaci.com/sw/sqlite/zipvfs.html

Thanks.

**Comment by zevv** [comment]
Yes, I've looked at zipfs, but it seems that it comes with a commercial license only. For good results compression has to be done at the database level: I did some experiments with compression the individual database records, but since these are all pretty small the effect of compression is not significant. 

A few days ago I have added Kyotocabinet (which is not the same as Tokyocabinet, what a terrible names), you could give this a try to see if it results in more portable databases.
