### ISSUE TITLE
Database version mismatch - workaround?

### ISSUE THREAD

**Issue by alperyilmaz** [zevv/duc#156]
I was using duc version: 1.3.3 and then decided to try duc version: 1.4.2. And I got database version mismatch error.
I got similar problem when I upgraded to 1.3.3 which didn't recognize the database created by previous version.
Is there a  workaround for this problem? For each new version every drive/disk needs to be indexed all over. Is it possible to convert older database version to newer database version somehow, maybe with tokyocabinet commands or by duc index command?

**Comment by zevv** [comment]
Quoting Alper Yilmaz (2016-12-06 00:37:19)

> I was using duc version: 1.3.3 and then decided to try duc version:
> 1.4.2.  And I got database version mismatch error.  I got similar
> problem when I upgraded to 1.3.3 which didn't recognize the database
> created by previous version.

True: every now and then Duc changes the underlying database model to be
able to support new features. Currently there is no workaround other
then to re-index the disks. 

For most users this is not a huge problem because they rebuild their
indexes periodically. For very large setups which take days to build an
index this can of course be a nuisance. In some casese it should be
possible to add code to Duc to support older versions and drop some of
the new functionality in this case, but this is just something I have
not bothered to do up to now.

The good news is that database changes have been coming less frequent
over the last versions, and there are no changes planned at this time.


--
:wq
^X^Cy^K^X^C^C^C^C
