### ISSUE TITLE
Query the duc database outside duc 

### ISSUE THREAD

**Issue by jbd** [zevv/duc#165]
Hello,

My initial goal was to play around with some web framework to output something like the duc cgi stuff,  but using python.

I was naively playing with the [Python binding for the LMDB](https://lmdb.readthedocs.io/en/release/) and the duc database. I quickly understood that if I want to use it, I would have to understand the format used (varint...) and reimplement it in some way in my python code unless I'm missing something obvious.

It would be nice to have an official libduc library which would provide access to the function declared in libduc/db.h. With this library, it would be quite trivial to use ctypes to access thoses functions from python.

What do you think ?

**Comment by zevv** [comment]
> My initial goal was to play around with some web framework to output
> something like the duc cgi stuff,  but using python.
> 
> I was naively playing with the [Python binding for the
> LMDB](https://lmdb.readthedocs.io/en/release/) and the duc database.
> I've quickly understand that if I want to use it, I would have to
> understand the format used (varint...) and reimplement it in some way
> in my python code unless I'm missing something obvious.

Yes. And I'd rather not expose this format by making it official and
documenting it, since that will make it much harder to make any changes
in the future.

> It would be nice to have an official libduc library which would
> provide access to the function declared in libduc/db.h. With this
> library, it would be quite trivial to use ctypes to access thoses
> functions from python.

That was the original design. Before Duc switched to autoconf/automake
my custom makefiles already built shared libs, but we decided to simply
link it all into one binary for sake of simplicity, for now. I guess
changing back to .so's should be a few minutes work for someone who
actually understands autoconf.

There are two libs:

- libduc: this handles indexing and database querying. Instead of
  accessing the raw database records there is a readdir()-like interface
  to get all the info. Export interface is in src/libduc/duc.h

- libduc-graph: used to generate graphs with cairo, html, openGL and
  SVG. This lib uses no internals from libduc, only the methods exposed 
  through duc.h. Export interface is in src/libduc-graph/duc-graph.h

(I've been hoping someone would one day write a flashy GTK app on top of
these libs, but no volunteers for that yet :))

And there is:

- duc: the command line tools. This is mostly glue to parse command
  lines and to provide user interfaces. Uses no inernals from either
  libs, only duc.h and duc-graph.h

I'd be happy to change back to the shared lib setup and include bindings
for various languages in the tree.

John, any opinions on this?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

>> My initial goal was to play around with some web framework to output
>> something like the duc cgi stuff, but using python.
>> 
>> I was naively playing with the [Python binding for the
>> LMDB](https://lmdb.readthedocs.io/en/release/) and the duc database.
>> I've quickly understand that if I want to use it, I would have to
>> understand the format used (varint...) and reimplement it in some way
>> in my python code unless I'm missing something obvious.

Ico> Yes. And I'd rather not expose this format by making it official
Ico> and documenting it, since that will make it much harder to make
Ico> any changes in the future.

It might be just that we increment the major number for such changes
and update the API.  No need for major backwards support if there's
some way to export to a neutral format that can be re-imported.
Maybe. 

>> It would be nice to have an official libduc library which would
>> provide access to the function declared in libduc/db.h. With this
>> library, it would be quite trivial to use ctypes to access thoses
>> functions from python.

Ico> That was the original design. Before Duc switched to
Ico> autoconf/automake my custom makefiles already built shared libs,
Ico> but we decided to simply link it all into one binary for sake of
Ico> simplicity, for now. I guess changing back to .so's should be a
Ico> few minutes work for someone who actually understands autoconf.

It shouldn't be too hard to do.  Since I did most of the autoconf
work, I'll try and find some time to look into this.  Been busy
helping friends move all afternoon, so not tonight.  *grin*

Ico> There are two libs:

Ico> - libduc: this handles indexing and database querying. Instead of
Ico> accessing the raw database records there is a readdir()-like interface
Ico> to get all the info. Export interface is in src/libduc/duc.h

Ico> - libduc-graph: used to generate graphs with cairo, html, openGL and
Ico> SVG. This lib uses no internals from libduc, only the methods exposed
Ico> through duc.h. Export interface is in src/libduc-graph/duc-graph.h

Ico> (I've been hoping someone would one day write a flashy GTK app on top of
Ico> these libs, but no volunteers for that yet :))

This might get me motivated to start learning perl/gtk ... 

Ico> And there is:

Ico> - duc: the command line tools. This is mostly glue to parse command
Ico> lines and to provide user interfaces. Uses no inernals from either
Ico> libs, only duc.h and duc-graph.h

Ico> I'd be happy to change back to the shared lib setup and include bindings
Ico> for various languages in the tree.

Ico> John, any opinions on this?

It depends on how automatic the binding setup is, and what needs to be
exposed.

If it's just to read the DB and run queries, then that's simple(r) to
accomplish.  Does any one have pointers to how to do this for python
or other languages?

**Comment by jbd** [comment]
> Does any one have pointers to how to do this for python or other languages?

Something like [swig](http://swig.org) would permit to generate decent bindings for a [bunch](http://swig.org/compare.html) of languages.

**Comment by zevv** [comment]
Quoting John (2016-12-31 01:18:54)
 
> It might be just that we increment the major number for such changes
> and update the API.  No need for major backwards support if there's
> some way to export to a neutral format that can be re-imported.
> Maybe. 

Well, it's just not a friendly format. In retrospective it would
probably have been better to use some kind of standard compact binary
serialization protocol like BSON, CBOR or Messagepack, this would
make parsing the database a bit easier for others.

> > It would be nice to have an official libduc library which would
> > provide access to the function declared in libduc/db.h. With this
> > library, it would be quite trivial to use ctypes to access thoses
> > functions from python.
> 
> Ico> That was the original design. Before Duc switched to
> Ico> autoconf/automake my custom makefiles already built shared libs,
> Ico> but we decided to simply link it all into one binary for sake of
> Ico> simplicity, for now. I guess changing back to .so's should be a
> Ico> few minutes work for someone who actually understands autoconf.
> 
> It shouldn't be too hard to do.  Since I did most of the autoconf
> work, I'll try and find some time to look into this.

Great, thanks for that. I've never grown to love autoconf...

> Ico> I'd be happy to change back to the shared lib setup and include bindings
> Ico> for various languages in the tree.
> 
> Ico> John, any opinions on this?
> 
> It depends on how automatic the binding setup is, and what needs to be
> exposed.

Both libs have a single header file (duc.h and duc-graph.h) which define
the public APIs, so this should be the only exposed interface. Basically
we only need to tell autoconf to build libduc and libduc-graph as shared
libraries and to install the tho header files somewhere in /usr/include.

> If it's just to read the DB and run queries, then that's simple(r) to
> accomplish. 

That, and indexing a file system. Basically all functions which are now
available on the duc command line too. See duc.h for the details.

> Does any one have pointers to how to do this for python or other
> languages?

It's not my goal to provide the bindings, but merely to make it possible
for others to do so by splitting up duc into its original library
design.


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Quoting jbd (2016-12-31 02:27:39)
> > Does any one have pointers to how to do this for python or other languages?
> 
> Something like [swig](http://swig.org) would permit to generate decent
> bindings for a [bunch](http://swig.org/compare.html) of languages. 

I don't think we should provide bindings, just facilitate and make it
possible for others to do so.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Hi John,

I've been fiddling around a bit and I think I got things setup almost
properly:

https://github.com/zevv/duc/tree/shared-libs

libduc and libduc-graph are now built as shared libs and are installed
in the proper place on 'make install'

I got some warnings from autoconf though, has something to do with
redefines in m4 macros somewhere deep inside:

````
configure.ac:24: warning: AC_COMPILE_IFELSE was called before
AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:314: AC_GNU_SOURCE is expanded from...
configure.ac:24: the top level
configure.ac:24: warning: AC_RUN_IFELSE was called before
AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:314: AC_GNU_SOURCE is expanded from...
configure.ac:24: the top level
configure.ac:24: warning: AC_COMPILE_IFELSE was called before
AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:314: AC_GNU_SOURCE is expanded from...
configure.ac:24: the top level
configure.ac:24: warning: AC_RUN_IFELSE was called before
AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:314: AC_GNU_SOURCE is expanded from...
configure.ac:24: the top level
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.a
````

I'm off for the day, I'll see if I can get things cleaned up soon.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by jbd** [comment]
> I don't think we should provide bindings, just facilitate and make it possible for others to do so.

I agree.

> I've been fiddling around a bit and I think I got things setup almost properly

Cool ! I'll play with that.

**Comment by l8gravely** [comment]
Ok, I've done the following as a simple test.


1.  Create the file src/libduc/duc.i with the following:

     %module duc
      %{
      /* Includes the header in the wrapper code */
      #include "duc.h"
      %}

      /* Parse the header file to generate wrappers */
      %include "duc.h"

2. cd src/libduc
3. swig -python duc.i
4. gcc -fpic -c duc_wrap.c duc.c -I. -I../../ -I/usr/include/python2.7
5. gcc -shared duc.o duc_wrap.o -o _duc.so
6. fire it up and watch it burn!

> python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import duc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    File "duc.py", line 28, in <module>
        _duc = swig_import_helper()
	  File "duc.py", line 24, in swig_import_helper
	      _mod = imp.load_module('_duc', fp, pathname,
	      description)
	      ImportError: ./_duc.so: undefined symbol:
	      duc_dir_openent


So I've obviously missed something... probably had to compile more *.o
files and included them into the lib.  And it loooks like I need to
include all the *.o, duh.  Time to setup something in the makefile to
do the work for me.

But I suspect that:

- make
- cd src/libduc
- gcc -fpic duc_wrap.c
- gcc -shared *.o -o _duc.so

and nope, not working.  Looks like python requires stuff to be
compiled with -fpic to make it work.  Hmm... might be a simple matter
to just re-configure duc to have that on by default if it won't cause
problems.

But the basic idea is almost there...  I'll see what I can do more on
this today, but maybe this is enough of a hint for someone else.

John

**Comment by zevv** [comment]
Quoting John (2016-12-31 16:21:09)

> So I've obviously missed something... probably had to compile more *.o
> files and included them into the lib.  And it loooks like I need to
> include all the *.o, duh.  Time to setup something in the makefile to
> do the work for me.
>
> [...]
> 
> But the basic idea is almost there...  I'll see what I can do more on
> this today, but maybe this is enough of a hint for someone else.

I have no clue about swig (I used it 10 years ago and hated it with all my
heart), but I've just added a proof of concept Lua binding to the
shared-library branch which works just fine.

This now works (Lua code ahead):

````
Duc = require "lduc"

-- Create duc context

duc = Duc:new()

-- Open database. The default database path is used if no file name is given

duc:open()

-- Open /tmp directory and list all files

dir = duc:dir_open("/tmp")

while true do
   ent = dir:read()
   if not ent then
      break
   end
   print(string.format("%-5.5s %7d %-30.30s %12d",
      ent.type, ent.size.count, ent.name, ent.size.actual))
end

````


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> Quoting John (2016-12-31 16:21:09)
>> So I've obviously missed something... probably had to compile more *.o
>> files and included them into the lib. And it loooks like I need to
>> include all the *.o, duh. Time to setup something in the makefile to
>> do the work for me.
>> 
>> [...]
>> 
>> But the basic idea is almost there... I'll see what I can do more on
>> this today, but maybe this is enough of a hint for someone else.

Ico> I have no clue about swig (I used it 10 years ago and hated it
Ico> with all my heart), but I've just added a proof of concept Lua
Ico> binding to the shared-library branch which works just fine.

Nice.  I need to look into this more to see what you did.  I don't
know Lua for beans, nor python really.

The nice thing with swig is that it should make it trivial to provide
bindings to multiple languages, and we can setup things so that we
provide the input swig files, and the generated files as well, so that
end users don't need to have swig installed at all.

Ico> This now works (Lua code ahead):

Ico> ````
Ico> Duc = require "lduc"

Ico> -- Create duc context

Ico> duc = Duc:new()

Ico> -- Open database. The default database path is used if no file name is given

Ico> duc:open()

Ico> -- Open /tmp directory and list all files

Ico> dir = duc:dir_open("/tmp")

Ico> while true do
Ico> ent = dir:read()
Ico> if not ent then
Ico> break
Ico> end
Ico> print(string.format("%-5.5s %7d %-30.30s %12d",
Ico> ent.type, ent.size.count, ent.name, ent.size.actual))
Ico> end

Now I think this is cool, because it gives us a way for people to
generate their own custom reports.  We should talk about other
language bindings we could think about.  I personally would like perl,
since I know that language.

Swig, which is trivial to use IMHO, looks like a great enabler.

I'm using the following pages to setup some SWIG support in
configure.ac for fun.  I know, I have a strange definition of fun.

http://stackoverflow.com/questions/5056606/how-to-use-autotools-to-build-python-interface-at-same-time-as-library


Anyway, happy new year to you all!

John

**Comment by jbd** [comment]
> In retrospective it would probably have been better to use some kind of standard compact binary serialization protocol like BSON, CBOR or Messagepack, this would make parsing the database a bit easier for others.

I like that idea very much =) [Caffe](https://github.com/BVLC/caffe) uses [google protobuf] (https://developers.google.com/protocol-buffers/) to store data in their LMDB or LevelDB backend.
