### ISSUE TITLE
ncdu import

### ISSUE THREAD

**Issue by noamraph** [zevv/duc#169]
Hi,

ncdu is a nice disk usage utility that has the option to store a file with all the size information. I installed it on a synology NAS using just the binary they provide.

It is much faster to create the index on the server than on a client, due to the required latency for each filesystem call. If you can add a feature to import the index of ncdu, it would be very nice - it would allow me to quickly create the index on the server, and then view it graphically on my computer.

Thanks,
Noam

**Comment by zevv** [comment]
Not planning on doing any importing yet. I assume you can't use Duc for the indexing on the Synology because there is no Duc package available for that platform?

**Comment by noamraph** [comment]
There are only a few packages for the synology platform. ncdu provide a
binary that includes the required libraries, that runs as is on the
Synology NAS.

**Comment by l8gravely** [comment]
I'm closing this for now since I personally have no real plans to write an importer, but we would accept any patches.  Please see the latest release of v1.5.0-rc1 which just came out.  And building a static only binary might not be too hard, though a bunch of libraries would have to be built statically first.
