### ISSUE TITLE
Add method to avoid I/O hogging

### ISSUE THREAD

**Issue by zevv** [zevv/duc#175]
Indexing is a pretty expensive jobs, I/O wise, and on busy systems this can be disruptive for other services. It would be nice if Duc would have some way to play nice with other processes.

Ideas:

- Add support for ioprio_set to set I/O scheduler policies. (con: Linux-only)

- Add a simple usleep() after or before reading each directory. con: (might be hard to tune right)

- Add a dynamic usleep() with some heuristics on system load average.

Ideas welcome

**Comment by l8gravely** [comment]
Ico> Indexing is a pretty expensive jobs, I/O wise, and on busy
Ico> systems this can be disruptive for other services. It would be
Ico> nice if Duc would have some way to play nice with other
Ico> processes.

Ico> Ideas:

Ico>   • Add support for ioprio_set to set I/O scheduler policies. (con: Linux-only)

Ico>   • Add a simple usleep() after or before reading each
Ico>     directory. con: (might be hard to tune right)

Ugh!  I want my indexing to be faster, not slower!

Ico>   • Add a dynamic usleep() with some heuristics on system load average.

The problem with system load is that it's not a great indicator of
where the problem is.  And I don't know of a good way.

But maybe, just maybe, having a switch (-S maybe?) to sleep after N
calls, or after a directory is indexed, might be ok.

Of course when you have a directory with more than 10k entries... life
is going to suck no matter what.

**Comment by zevv** [comment]
Quoting John (2017-02-01 18:29:13)

> The problem with system load is that it's not a great indicator of
> where the problem is.  And I don't know of a good way.

It's not a good indicator, but it might be just good enough. System load
is an indication of how many processes are waiting to get work done, but
can not get to do it because the system is too busy. Walking file
systems is an excellent way to get your load op: a lot of seeking going
on, a lot of processes waiting for their I/O requests to happen, poof
goes your load.

I've added a tiny piece of code that does a very simple thing: it
monitors the load every 10 seconds, and adjusts a usleep() timer
interval so that Duc slows down to keep the load below a configured
number. Simply, but does the job just fine for me.

I'm doing some more tweaking, will push the result for others to test.

> But maybe, just maybe, having a switch (-S maybe?) to sleep after N
> calls, or after a directory is indexed, might be ok.
> 
> Of course when you have a directory with more than 10k entries... life
> is going to suck no matter what.

Just sleep() after X lstat() calls instead of at the start of each dir,
this will spread the load just fine.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
Another random idea is to take a look at using Cgroups to limit access to storage devices. That would presumably be limited to Linux, and the current controllers are probably focused towards controlling bulk data rather than metadata operations?

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
Quoting stuartthebruce (2017-02-01 21:41:21)

> Another random idea is to take a look at using Cgroups to limit access
> to storage devices. That would presumably be limited to Linux, and the
> current controllers are probably focused towards controlling bulk data
> rather than metadata operations?

I've briefly looked into that, but the lack of portability put me off a
bit. I don't know anything about the implementation, so I'd have to look
into this to see if there is any support for controlling metadata.
 
--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> Quoting stuartthebruce (2017-02-01 21:41:21)
>> Another random idea is to take a look at using Cgroups to limit access
>> to storage devices. That would presumably be limited to Linux, and the
>> current controllers are probably focused towards controlling bulk data
>> rather than metadata operations?

Ico> I've briefly looked into that, but the lack of portability put me off a
Ico> bit. I don't know anything about the implementation, so I'd have to look
Ico> into this to see if there is any support for controlling metadata.

Can't people just run it under 'nice' if they want it to be slower?

But putting in an option that's disabled by default, to sleep a tiny
bit every 100 stat() calls might be the thing to do as a quick hack.
And hack it is....

**Comment by zevv** [comment]
Closing - run with `nice` or `ionice`
