### ISSUE TITLE
Read "du" output

### ISSUE THREAD

**Issue by antofthy** [zevv/duc#193]
I need to view disk usage of systems with restricted access (remote, network/software restrictions, root only, etc).
I can generate "du" listings and want to know if "duc" can import those for display.
I can find no reference to this in the "duc" help or manpages.

**Comment by zevv** [comment]
Quoting Anthony Thyssen (2018-04-12 04:33:38)
> I need to view disk usage of systems with restricted access (remote, network/software restrictions, root only, etc).
> I can generate "du" listings and want to know if "duc" can import those for display.
> I can find no reference to this in the "duc" help or manpages.

Reading `du` output is not possible at this time. This has come up
before but no solution available yet. See

  https://github.com/zevv/duc/issues/180


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by antofthy** [comment]
If you need more information that what "du" provides (dates, permissions etc) then reading the output of a find {dir} -ls  may be an alternative.   Or as duc  uses a database, a script that converts "du" or "find-ls" output to that database is an alternative to building it it.

Essentially It would be nice to be able to make use of "duc"s graphical display engine with other hierarchical data, allowing it to be used for many other things, many of which has been described in other issues (like only show newer files).  I have done similar things in the past with a different hierarchical display programs.  IE "xdu", and its more modern "xdiskusage",  though these have pretty horrible display of the data, and no re-use database.

Just food for thought!

**Comment by l8gravely** [comment]
Anthony> I need to view disk usage of systems with restricted access (remote, network/
Anthony> software restrictions, root only, etc).

So you can put a statically linked copy of 'duc' onto these systems
and use that to generate the index which you export to the main server
for display services?  

Anthony> I can generate "du" listings and want to know if "duc" can
Anthony> import those for display.  I can find no reference to this in
Anthony> the "duc" help or manpages.

At this time, as Ico says, it's not possible.  If you want to write
the tool to do so... that would be awesome.  But it would be difficult
and slow.  And since you're *already* exporting data from these
restricted systems, it seems simpler to put a copy of duc on there to
index them from the get go.

There must be some policy in place for allowing access, otherwise
what use are these systems?  Though I suspect it's "nothing but vendor
supplied tools and our application".  Which is a shame.  Unless of
course you just make 'duc' part of your application.  Heh.

John
