### ISSUE TITLE
Support slicing floorplan in GUI

### ISSUE THREAD

**Issue by PanderMusubi** [zevv/duc#208]
Please, support slicing floorplan representation in GUI.

https://en.wikipedia.org/wiki/Floorplan_(microelectronics)#Sliceable_floorplans

**Comment by zevv** [comment]
I've been looking into alternative mapping methods before, including the treemap layout. I have tried some implementations, but I'm never happy with the results. I think this is mainly because of the overlapping nature of the layout, which makes it hard to navigate.

I'll see if I can find an old branch with an implementation and merge it to master so people can take a peek and give their opinions

**Comment by zevv** [comment]
https://www.cc.gatech.edu/~stasko/7450/16/Notes/tree2.pdf


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by PanderMusubi** [comment]
Nice overview.

Yes, to get windirstat-like view. Unfortunately, I'm not going to make a PR for this. Working on other FOSS projects.

**Comment by zevv** [comment]
Sorry, I can't get myself to like this kind of view. It's very hard to understand the structure of folders and subfolders, and a view with a depth of more then one or two levels gets way to messy. The strength of Duc lies in the sunburst view.

I'm closing this as a wontfix
