### ISSUE TITLE
The ncurses library was not found, which is needed for ui support

### ISSUE THREAD

**Issue by AlexLeung** [zevv/duc#218]
I'm getting this error even after a successful run of 

```
sudo yum install ncurses-devel
```

**Comment by l8gravely** [comment]
Alex> I'm getting this error even after a successful run of
Alex> sudo yum install ncurses-devel

So which Redhat system are you on?  RHEL?  Fedora?  CentOS?  How did
you install duc?  Did you compile from scratch?  You didn't include
the full error to help us.

It might also be good to do:

   ldd duc

so we see exactly what library version it's looking for.

You might need to do:

  sudo yum install ncurses-libs.i686 ncurses-libs.x86_64 ncurses

to make sure you pull in all the stuff you need.  But more details
please!

John

**Comment by AlexLeung** [comment]
OS is Amazon EC2 Bare Metal Linux, which I believe is a derivative of RHEL.

Downloaded the 1.4.4 source .tgz and installed via 
```
./configure
make
sudo make install
```
Ended up using the flag which installs without the ncurses gui since I ran out of time. The X11 GUI is sufficient for my needs.

I would try again, but I'm worried I will end up uninstalling incorrectly so I'd rather just keep the current installation. If this was managed using snappy then I wouldn't mind trying again.

I believe the error I posted was the full error. I don't remember seeing any further information.

**Comment by l8gravely** [comment]
>>>>> "Alex" == Alex Leung <notifications@github.com> writes:

Alex> OS is Amazon EC2 Bare Metal Linux, which I believe is a
Alex> derivative of RHEL.  Downloaded the 1.4.4 source .tgz and
Alex> installed via

Alex> ./configure
Alex> make
Alex> sudo make install

Alex> Ended up using the flag which installs without the ncurses gui
Alex> since I ran out of time. The X11 GUI is sufficient for my needs.

Ok, this is useful news, I'll see if I can spin up an instance and
test it out.  But I suspect you didn't install the proper ncurses
library, but we could also be just mis-detecting the install.

Alex> I would try again, but I'm worried I will end up uninstalling
Alex> incorrectly so I'd rather just keep the current installation. If
Alex> this was managed using snappy then I wouldn't mind trying again.

There's no need to un-install at all, just do a make clean,
re-configure and then rebuild.  You can test without installing then.

Could you send the config.log of your setup maybe?  

Alex> I believe the error I posted was the full error. I don't
Alex> remember seeing any further information.

The build log would help.

**Comment by l8gravely** [comment]
There's been no further input, so I'm closing this ticket for now.  If you can give us more info, we would be happy to work with you on this.
