### ISSUE TITLE
duc is slow here

### ISSUE THREAD

**Issue by 3rdChimp** [zevv/duc#221]
Hello
I have a big external disk of 4 TB and it's full with incremental backup relying on hard-links

I want to inspect it to see how all the space is used, and I run duc

The first time, it crashed after 1h (not enough memory)
The second time, it took 27h.  I forgot to activate the -H options, so it counted multiple hard links (said the tisk contents 27TB of data!)

I now started another run with the -H option

I just wanted to know if you have any idea what is wrong (apart, say, my disks are slow).

**Comment by 3rdChimp** [comment]
Here is the STDOUT:

root@XXX:/mnt/M# date ; time duc index --database=/var/lib/ncdu/ncdu_data_indexes/3-mercredi/_mnt_M.duc.db -x --exclude=/var/lib/ncdu/ncdu_data_indexes/3-mercredi/_mnt_M.duc.db /mnt/M ; date
mercredi 7 août 2019, 23:03:56 (UTC+0200)


real    1637m34,642s
user    6m11,700s
sys     7m4,208s
vendredi 9 août 2019, 02:21:31 (UTC+0200)
root@XXX:/mnt/M# 

```

**Comment by zevv** [comment]
Quoting 3rdChimp (2019-08-09 19:08:47)

> I just wanted to know if you have any idea what is wrong (apart, say, my disks are slow).

Duc does not have much overhead apart from the system calls used to scan
your file system. could you compare with a run of a recursive "ls -lR"?
if that is significantly faster your have hit something worth
investigating.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by 3rdChimp** [comment]
I did 

find . -type f | wc -l

and it ran for 8h

**Comment by 3rdChimp** [comment]
Number of files: 26105015

**Comment by zevv** [comment]
Quoting 3rdChimp (2019-08-09 20:21:56)
> I did 
> 
> find . -type f | wc -l

That is not really a fair comparison, because in this case "find" only
has to do a readdir() for all directories without accessing the metadata
of each individual file - this is what Duc needs to do in order to get
all file sizes and modes.

If you ask find to print file size as well it will do a lstat() of all
the entries, just like Duc:

  find . -printf '%s %p\n"

I expect this runs for the same order of magnitude as duc.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by 3rdChimp** [comment]
Thanks

As soon as the ongoing index finishes (in a few days), I will try this find.

**Comment by l8gravely** [comment]
3rdChimp> As soon as the ongoing index finishes (in a few days), I will try this find.

I think the problem is you have 26 million files, and one spindle, so
your IOPs is really really low.  It just can't do reads any quicker.

But it would also help if you could tell us what system you're doing
this on, which version of duc, etc.  Please send us:

     uname -a
     duc --version

so we get a better idea of where the possible problem is.

John

**Comment by zevv** [comment]
Quoting 3rdChimp (2019-08-09 22:19:23)
> Thanks
> 
> As soon as the ongoing index finishes (in a few days), I will try this find. 

There is surely no need to scan your whole file system to get conclusive
results? You could just drop your caches and buffers (echo 3 >
/proc/sys/vm/drop_caches) and scan only a small directory in a few
seconds or minutes?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by 3rdChimp** [comment]
You guys are very smart

>I expect this runs for the same order of magnitude as duc.

So the answer is YES

I select a smaller directory containing 50000 files

root@XXX:~# echo 3 > /proc/sys/vm/drop_caches                                                                                                                          
root@XXX:~# date ; time duc index -x $DATA
samedi 10 août 2019, 16:52:00 (UTC+0200)

real    0m54,628s
user    0m0,080s
sys     0m0,372s
root@XXX:~# echo 3 > /proc/sys/vm/drop_caches
root@XXX:~# cd $DATA
root@XXX:data# find . -printf '%s %p\n' | cat > /dev/null
samedi 10 août 2019, 16:54:17 (UTC+0200)

real    0m58,757s
user    0m0,044s
sys     0m0,344s
root@XXX:data# 


>uname -a

Linux XXX 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux

>duc --version

duc version: 1.4.3
options: cairo x11 ui tokyocabinet

> I think the problem is you have 26 million files, and one spindle, 

Is this some kind of record?

**Comment by zevv** [comment]
Quoting 3rdChimp (2019-08-10 17:00:12)

> So the answer is YES

So the conclusion would be that the problem is not in Duc, glad to hear
that.

> > I think the problem is you have 26 million files, and one spindle, 
> 
> Is this some kind of record?

It is on the high side, but it is a typical number of files when using
hard-link based backups. I have a similar backup running on a ten-user
system and I also have about 30M files, the majority hard links, on a
2TB file system.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
>>>>> "Ico" == Ico Doornekamp <notifications@github.com> writes:

Ico> Quoting 3rdChimp (2019-08-10 17:00:12)
>> So the answer is YES

Ico> So the conclusion would be that the problem is not in Duc, glad
Ico> to hear that.

Exactly, you have run into exactly the same problem I have at $WORK,
but even worse since you have just a single spindle I'm on running on
Netapps with over a hundred spindles.  Still sucks!

>> > I think the problem is you have 26 million files, and one spindle,
>> 
>> Is this some kind of record?

Ico> It is on the high side, but it is a typical number of files when
Ico> using hard-link based backups. I have a similar backup running on
Ico> a ten-user system and I also have about 30M files, the majority
Ico> hard links, on a 2TB file system.

I've got a 10tb file system at $WORK with 75+ million files.  It
*sucks* for backups, esp incrementals.
