### ISSUE TITLE
duc coredump when scanning it's own index

### ISSUE THREAD

**Issue by 3rdChimp** [zevv/duc#222]
Duc was crashing with coredump every time I ran it.

 index --database=/var/lib/ncdu/ncdu_data_indexes/3-mercredi/_mnt_M.duc.db -x  /

Then I noticed that the index is inside the filesystem it scans.

If I exclude it, it does not crashed any more

duc index --database=/var/lib/ncdu/ncdu_data_indexes/3-mercredi/_mnt_M.duc.db -x --exclude=/var/lib/ncdu/ncdu_data_indexes/3-mercredi/_mnt_M.duc.db /

**Comment by zevv** [comment]
Quoting 3rdChimp (2019-08-09 19:11:15)
> Duc was crashing with coredump every time I ran it.
> 
>  index
>  --database=/var/lib/ncdu/ncdu_data_indexes/3-mercredi/_mnt_M.duc.db
>  -x  /
> 
> Then I noticed that the index is inside the filesystem it scans.
> 
> If I exclude it, it does not crashed any more

Interesting, I scanned ducs own database tons of times without issues, I
do not see why this would crash. Any sigsegvs are usually related to
libtokyocabint behaving bad with a corrupted database file, but its
worth figuring out what is wrong here.

Do you have the skills to build a debug version from source and run in
gdb to get a backtrace, or time to let us help you figure out how to do
that?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by 3rdChimp** [comment]
Yes, I should try that
First, let me reproduce and get you the STDERR

**Comment by 3rdChimp** [comment]
[ncdu_FS_from_root.sh.2019-08-03.log-2019-08-05.slash.log](https://github.com/zevv/duc/files/3487647/ncdu_FS_from_root.sh.2019-08-03.log-2019-08-05.slash.log)

**Comment by zevv** [comment]
As expected, the problem is in libtokyocabinet. This is the default
database engine used by Duc because of the good performance/size
tradeoff, but is is picky about corrupted database files - if you abort
an index run with ^C it is easy to get this kind of problems. I guess we
should really pick a different default engine, all these crashes give
Duc a bad name :(

Delete your database and create a new one, and you should be fine.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by 3rdChimp** [comment]
I cannot reproduce the problem.
If it comes beck, I'll purge my DB.

thanks

**Comment by 3rdChimp** [comment]
I had duc running, then canceled it (^C), then reun it again, it it crashed.
But not alBut it does not always play like that. Sometime, cancel does not corrupt the DB.

So idea: why not delete the DB before indexes?

I read somewere that duc is incremental.

So is it quicker to index and update the database than index and recreate db from scratch?

**Comment by l8gravely** [comment]
>>>>> "3rdChimp" == 3rdChimp  <notifications@github.com> writes:

3rdChimp> I had duc running, then canceled it (^C), then reun it
3rdChimp> again, it it crashed.  But not alBut it does not always play
3rdChimp> like that. Sometime, cancel does not corrupt the DB.

As Ico said, it's due to TokyoCabinet not being very robust when the
DB is corrupted.  Not much we can do except to move to a new backend
which is more robust.

3rdChimp> So idea: why not delete the DB before indexes?

Because you didn't ask for it.  And you might be doing an update of
the DB, where you add in new directories to be scanned.

I personally have my scripts setup to index to a new DB, then when
it's done, I move the old one out of the way and put the new one in
it's place, because I have my users look at usage via the web
interface only, they don't touch the CLI or GUI at all. 

3rdChimp> I read somewere that duc is incremental.

No, it's not really.  What you can do is index your filesystem, then
when you re-index it, it will pickup the changes in terms of added or
removed files/directories.  But it's not really incremental since it
still needs to scan the entire directory tree no matter what to build
the database.

3rdChimp> So is it quicker to index and update the database than index
3rdChimp> and recreate db from scratch?

It's all limited by the speed of your disk system, since duc is doing
a find and stat of all files/directories.  It's not really CPU bound
at all, or even memory bound.  It's purely how fast is the storage
subsystem the directory is located on.

John
