### ISSUE TITLE
`duc gui` command remains running after window closed

### ISSUE THREAD

**Issue by aduros** [zevv/duc#265]
When `duc gui` is run and then the GUI window closed, the command keeps running in the terminal until I CTRL-C it.

Output from `duc --version`:
```
duc version: 1.4.4
options: cairo x11 ui tokyocabinet
```

I'm a huge fan of duc, thanks for all your hard work!

**Comment by zevv** [comment]
Hm, can't reproduce here, although I do get a `XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 2782 requests (2281 known processed) with 0 events remaining.` at exit, which is of course not nice.

I see that the main XEvent loop doesn't even handle DestroyWindow, so somthing is missing here.

**Comment by l8gravely** [comment]
>>>>> "Bruno" == Bruno Garcia <notifications@github.com> writes:

Bruno> When duc gui is run and then the GUI window closed, the command
Bruno> keeps running in the terminal until I CTRL-C it.

What distro are you using, and which window manager?  Can you give
more details please?  

Bruno> Output from duc --version:

Bruno> duc version: 1.4.4
Bruno> options: cairo x11 ui tokyocabinet

Bruno> I'm a huge fan of duc, thanks for all your hard work!

Bruno> —
Bruno> You are receiving this because you are subscribed to this thread.
Bruno> Reply to this email directly, view it on GitHub, or unsubscribe.*

**Comment by aduros** [comment]
My WM i3 + Gnome Flashback. The distro is an Ubuntu derivative called Regolith. Duc was installed with apt.

Thanks for the fix! I'm not set up to build duc right now, but I'll verify when I can.

**Comment by l8gravely** [comment]
>>>>> "Bruno" == Bruno Garcia <notifications@github.com> writes:

Bruno> My WM i3 + Gnome Flashback. The distro is an Ubuntu derivative
Bruno> called Regolith. Duc was installed with apt.

Bruno> Thanks for the fix! I'm not set up to build duc right now, but
Bruno> I'll verify when I can.

It should be pretty simple:

  apt-get install -y build-essential git
  apt-get install -y libncursesw5-dev libcairo2-dev libpango1.0-dev liblmdb-dev

And of course you'll need to add in libtokyo...-dev package, then


  git clone https://github.com/zevv/duc/
  cd duc
  autoreconf -i
  ./configure
  make

and off you go.
