### ISSUE TITLE
Enhancement: allow keeping symlink name as root directory

### ISSUE THREAD

**Issue by ghuls** [zevv/duc#27]
It would be useful in my case that duc doesn't resolve symlinks of the root index directory.
```
# Index directory which is a symlink.
#  /media/my_symlink_dir points to /media/data.
duc index /media/my_symlink_dir
```
The duc database will display /media/data as root dir.

At least in the commandline version of realpath, you can do the following:
```
$ realpath /media/my_symlink_dir
/media/data

$ realpath -s /media/my_symlink_dir
/media/my_symlink_dir

$ realpath -s /./media/../media/my_symlink_dir
/media/my_symlink_dir
```

I have /media/data directories on different NFS servers, which I want to index locally, but I want the path names that are visible start with /media/server_name instead of /media/data (I know this  /media/server_name already works when you have the symlink, but it is not displayed).

**Comment by zevv** [comment]
I'm not sure changing this behaviour was the right thing to do, looking back I think it is better to properly de-reference symlinks since the current behaviour is hard to understand.  I've run into problems with this several times over the last months, so I'm revering the code back to realpath().

 Let me know if this causes too big problems for you so we can discuss solutions.
