### ISSUE TITLE
Add df (disk free) info to database

### ISSUE THREAD

**Issue by akkemp** [zevv/duc#271]
It would be great to have the option to show unused space. So in the sunburst this would need to be toggleable in case it saturates the used space - probably just by creating a meta node of used / unused which would allow you to click through as normal

**Comment by l8gravely** [comment]
So the problem here is that duc is NOT a real-time tool for investigating filesystems.  First you index, then you view the results, which can be days, weeks or months later.  Keeping the index upto date in realtime isn't possible, which is why duc (and previously philesight) were first setup.  

I'm closing this issue.
