### ISSUE TITLE
Feature request : Delete files and directories from ui

### ISSUE THREAD

**Issue by crile** [zevv/duc#276]
Hi, great tool but we always want more right ?

Is it possible to add interactive action in the ui ? 

For example, type "d" shows a "popup" "Do you want to remove this file/directory ? (y/n)"

I use ncdu which do that but duc comes with nice graph.

Thanks

**Comment by l8gravely** [comment]
>>>>> "Cyril" == Cyril SANTUNE ***@***.***> writes:

Cyril> Hi, great tool but we always want more right ?
Cyril> Is it possible to add interactive action in the ui ?

Not really.  duc is two seperate tools in one.  The first tool is the
indexer which crawls the filesystem(s) and builds the DB of data.  The
second is the more interactive GUI and web based tools which let you
explore the data in the DB.

There are other requests for a feature like this.  We haven't really
spent any time implenting it, because once you make changes, then you
have to re-index the DB, which can be a long process.  I have some
15Tb volumes with 60 million files, which takes hours to re-index.  

Cyril> For example, type "d" shows a "popup" "Do you want to remove
Cyril> this file/directory ? (y/n)"

Cyril> I use ncdu which do that but duc comes with nice graph.

It might be possible to build in a feature which outputs a command
file which could be fed to 'rm' with a list of files/directories to
delete.  Then you could run that tool afterwards.

But again, re-indexing the DB and keeping them in sync, especially for
large filesystems, is a nightmare.  Duc really isn't designed for
smaller systems.

John

**Comment by crile** [comment]
I understand, thanks for your answer
