### ISSUE TITLE
Segmentation fault on indexing

### ISSUE THREAD

**Issue by halloleo** [zevv/duc#290]
Firstly thanks for duc. I really like the concept of one indexer and mutiple visualisation frontends.

I've installed version 1.4.4 (with options: cairo opengl ui tokyocabinet) via `brew` on macOS Catalina and started indexing with

    sudo duc index -xp /

Unfortunately I get a crash:

```
[-----#--] Indexed 8.8Gb in 61.0K files and 6.9K directories
Segmentation fault
```

When I run the same with `--debug` I see a log that starts and ends like this:

```
Writing to database "/Users/me/.duc.db"[K
>> /[K
  > 25 0 home[K
>> usr[K
>> bin[K
.
.
.
<< .brew actual:2186 apparent:4096[K
>> include[K
>> gobject-introspection-1.0[K
    8052 8192 girepository.h[K
    1863 4096 gipropertyinfo.h[K
    2572 4096 givfuncinfo.h[K
    3418 4096 giinterfaceinfo.h[K
    1769 4096 giconstantinfo.h[K
    4890 8192 gitypeinfo.h[K
    1696 4096 gisignalinfo.h[K
    2558 4096 giunioninfo.h[K
    6153 8192 giobjectinfo.h[K
    2622 4096 giarginfo.h[K
    2327 4096 gitypelib.h[K
    4523 8192 gicallableinfo.h[K
    2403 4096 gistructinfo.h[K
    2129 4096 gifieldinfo.h[K
    3274 4096 gibaseinfo.h[K
    7019 8192 giversionmacros.h[K
    4616 8192 girffi.h[K
    13593 16384 gitypes.h[K
    2363 4096 giregisteredtypeinfo.h[K
    1578 4096 giversion.h[K
    2348 4096 gienuminfo.h[K
    2877 4096 gifunctioninfo.h[K
<< gobject-introspection-1.0 actual:84643 apparent:126976[K
```

What's happening here? Any easy way for me to fix this?

**Comment by l8gravely** [comment]
>>>>> "halloleo" == halloleo  ***@***.***> writes:

halloleo> Firstly thanks for duc. I really like the concept of one
halloleo> indexer and mutiple visualisation frontends.

Thanks!

halloleo> I've installed version 1.4.4 (with options: cairo opengl ui
halloleo> tokyocabinet) via brew on macOS Catalina and started
halloleo> indexing with

This is something I have no experience with, since I don't have a Mac
or any compilation setup for Macs.  Do you know who compiled and put
this out on brew?  Can you reach out to them?

Also, if you can compile on your mac, maybe you could pull down the
latest code from github with:

  git clone https://gitbub.com/zevv/duc duc

and try to compile it.  

halloleo> sudo duc index -xp /

halloleo> Unfortunately I get a crash:

halloleo> [-----#--] Indexed 8.8Gb in 61.0K files and 6.9K directories
halloleo> Segmentation fault

halloleo> When I run the same with --debug I see a log that starts and ends like this:

halloleo> Writing to database "/Users/me/.duc.db"�[K
>>> /�[K
>> 25 0 home�[K
>>> usr�[K
>>> bin�[K
halloleo> .
halloleo> .
halloleo> .
halloleo> << .brew actual:2186 apparent:4096�[K
>>> include�[K
>>> gobject-introspection-1.0�[K
halloleo>     8052 8192 girepository.h�[K
halloleo>     1863 4096 gipropertyinfo.h�[K
halloleo>     2572 4096 givfuncinfo.h�[K
halloleo>     3418 4096 giinterfaceinfo.h�[K
halloleo>     1769 4096 giconstantinfo.h�[K
halloleo>     4890 8192 gitypeinfo.h�[K
halloleo>     1696 4096 gisignalinfo.h�[K
halloleo>     2558 4096 giunioninfo.h�[K
halloleo>     6153 8192 giobjectinfo.h�[K
halloleo>     2622 4096 giarginfo.h�[K
halloleo>     2327 4096 gitypelib.h�[K
halloleo>     4523 8192 gicallableinfo.h�[K
halloleo>     2403 4096 gistructinfo.h�[K
halloleo>     2129 4096 gifieldinfo.h�[K
halloleo>     3274 4096 gibaseinfo.h�[K
halloleo>     7019 8192 giversionmacros.h�[K
halloleo>     4616 8192 girffi.h�[K
halloleo>     13593 16384 gitypes.h�[K
halloleo>     2363 4096 giregisteredtypeinfo.h�[K
halloleo>     1578 4096 giversion.h�[K
halloleo>     2348 4096 gienuminfo.h�[K
halloleo>     2877 4096 gifunctioninfo.h�[K
halloleo> << gobject-introspection-1.0 actual:84643 apparent:126976�[K

halloleo> What's happening here? Any easy way for me to fix this?

It's not really clear to me unfortunately, but maybe it's an old
version of duc compiled on an old version of MacOS which is getting
tripped up?

My only real suggestion is to try and compile it yourself with the
latest versions from brew of the various libraries and tools.

Cheers,
John

**Comment by halloleo** [comment]
Thanks John, for trying to helping me out. Much appreciated!

I followed your suggestion and now downloaded the current release tar `duc-1.4.4.tar.gz` from GitHub, then compiled and installed it.

I still get the Segmentation fault and the debug output looks very similar ending with

    << gobject-introspection-1.0 actual:84643 apparent:126976[K


Is it worth it to send you the full debug output? Or can I somehow even increase the information available for you?

**Comment by l8gravely** [comment]
>>>>> "halloleo" == halloleo  ***@***.***> writes:

halloleo> Thanks John, for trying to helping me out. Much appreciated!
halloleo> I followed your suggestion and now downloaded the current
halloleo> release tar duc-1.4.4.tar.gz from GitHub, then compiled and
halloleo> installed it.

Can you instead use git and pull down the latest version from there?
I've been meaning to do a release for quite a while, but I keep
getting distracted by life.

    git clone https://github.com/zevv/duc duc

Should pull down the source and let you compile it.  

halloleo> I still get the Segmentation fault and the debug output
halloleo> looks very similar ending with

halloleo> << gobject-introspection-1.0 actual:84643 apparent:126976�[K

This doesn't really tell me much, I'd need to see the full output to
even start making a guess.  What would also help is seeing the
'config.log' file you go when you did the './configure' script to
setup things. 

halloleo> Is it worth it to send you the full debug output? Or can I
halloleo> somehow even increase the information available for you?

As I asked for before, more details on your environment and OS version
would really help.  How did you install 'gcc' on your Mac?  Just used
the latest 'homebrew' ports?   I'm really clueless on MacOS, so assume
I know knowing and spell it out.

**Comment by halloleo** [comment]
> Can you instead use git and pull down the latest version from there?

I've just done that:

```
$ duc --version
duc version: 1.4.5-rc1
```

However I still get

```
$ sudo duc index -xp  / --debug
[--#-----] Indexed 9.0Gb in 62.5K files and 7.1K directories
Segmentation fault
```

> I'd need to see the full output to even start making a guess. 

Please find the stderr output in [this gist][err].

  [err]: https://gist.github.com/halloleo/edf4e08fe02336139b26584321f917d6

> What would also help is seeing the 'config.log' file you go when you did the
> './configure' script to setup things.

I've uploaded the config.log to [this gist][cfg].

  [cfg]: https://gist.github.com/halloleo/0f7f2ec03fc4f3a138bd06b96a2ef151

> More details on your environment and OS version would really help. 

macOS 10.15.7, Intel MacBook from 2012

> How did you install 'gcc' on your Mac? Just used the latest 'homebrew' ports?

No, `gcc` is from the default clang-gcc from the Apple developer tools:

```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Thanks heaps for looking at this!

**Comment by l8gravely** [comment]
>>>>> "halloleo" == halloleo  ***@***.***> writes:

halloleo>     Can you instead use git and pull down the latest version from there?
halloleo> I've just done that:

halloleo> $ duc --version
halloleo> duc version: 1.4.5-rc1

halloleo> However I still get

halloleo> $ sudo duc index -xp  / --debug
halloleo> [--#-----] Indexed 9.0Gb in 62.5K files and 7.1K directories
halloleo> Segmentation fault

Ok, can you just try to do:

  sudo duc index -xp /bin

and if that works, do:

  sudo du index -xp /gobject-introspection-1.0

and also maybe give us the output of:

  sudo du -sh /*

as a double check.  Does duc dump core on you?  If would be great if
you could do:

  gdb duc core
  gdb> bt

to show a back trace of where it crashes.

halloleo>     I'd need to see the full output to even start making a guess.
   
halloleo> Please find the stderr output in this gist.

Not really helpful unfortnately.  But it does look to be dying when
reading /gobject-introspection-1.0 which I can't tell if it's a
directory or a file.  

halloleo>     What would also help is seeing the 'config.log' file you
halloleo>     go when you did the './configure' script to setup
halloleo>     things.
   
halloleo> I've uploaded the config.log to this gist.

Thanks, that all looks ok from what I see.

halloleo>     More details on your environment and OS version would really help.
   
halloleo> macOS 10.15.7, Intel MacBook from 2012

halloleo>     How did you install 'gcc' on your Mac? Just used the latest 'homebrew' ports?
   
halloleo> No, gcc is from the default clang-gcc from the Apple developer tools:

halloleo> $ gcc --version
halloleo> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
halloleo> Apple clang version 12.0.0 (clang-1200.0.32.29)
halloleo> Target: x86_64-apple-darwin19.6.0
halloleo> Thread model: posix
halloleo> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

halloleo> Thanks heaps for looking at this!

Could you maybe configure it with:

   ./configure --disable-x11 --disable-opengl --disable-cairo

And then try that compile to see if it crashes.

You might need to do:

  ulimit -c unlimited

to allow it to dump core, not sure.  But then you could do the:

  gdb duc core

Which might have the core in /cores/.... but who knows?

Trying to get the smallest test case possible would be a big help.

John

**Comment by halloleo** [comment]
> Could you maybe configure it with:
>```
>  ./configure --disable-x11 --disable-opengl --disable-cairo
> ```
> And then try that compile to see if it crashes.

This works! Now the indexing gets over the initial couple of GB! 

Thanks heaps!
