### ISSUE TITLE
[DUC] disk space calculation

### ISSUE THREAD

**Issue by ydrocourt** [zevv/duc#311]
Hello 
I have a rather large file system with more than 400 TB with a very large number of files.
I have calculated the index of all the files at instant T. This took several days to complete. and I now want to track the data usage on this file system.
this file system is obviously not static and things get added to and deleted from it every days. The structure does not change however ..only new folder are added to the child directories.
ex I have /data/folderN/year/month/day/, in this case things are added to year/month/day, but the parent structure does not change (/data/folderN/).

Is it necessary to recalculate every single time the index to get a accurate size consumption? I have made a test, producing a plot yesterday and a plot today and the file size has not changed, when I would have expected it to have change. Hence my question.

Thank you in advance for the feedback you will provide.
best regards
Yoann

**Comment by l8gravely** [comment]
>>>>> "ydrocourt" == ydrocourt  ***@***.***> writes:


> I have a rather large file system with more than 400 TB with a very
> large number of files.

> I have calculated the index of all the files at instant T. This took
> several days to complete. and I now want to track the data usage on
> this file system.

You want to track the *change* in usage.  And this is hard, because
duc needs to re-scan the whole filesystem to see what has changed.  

> this file system is obviously not static and things get added to and
> deleted from it every days.  The structure does not change however
> ..only new folder are added to the child directories.  ex I have
> /data/folderN/year/month/day/, in this case things are added to
> year/month/day, but the parent structure does not change
> (/data/folderN/).

How about deletions?  How are they done?  

> Is it necessary to recalculate every single time the index to get a
> accurate size consumption? I have made a test, producing a plot
> yesterday and a plot today and the file size has not changed, when I
> would have expected it to have change. Hence my question.

Just plotting one day to the next won't show any changes unless you
update the DB.  For large filesystems like that (mine is 15tb, 30
million files) I only did scans weekly because it took so long.  

In your case, maybe what I would do is break it down into sub-areas,
and index those that are changing, and ignorning those that don't
change.

Now I admit it's harder to see the changes over time because we don't
have a way to querying multiple dbs together into one display.  If
someone wants to provide this code, we would love it!

**Comment by ydrocourt** [comment]
Thank you for your answer, It is a bit disappointing. I will try to experiment by stopping the index calculation at a higher level (not scanning the whole tree down.), maybe this will still get the size while saving time of scan?
thanks a lot, and hopefully such an option will come in the future.
best regards
Yoann

**Comment by l8gravely** [comment]
We'd be happy to accept code which could build multiple indexes and show the differences between them, but it's not in our roadmap right now.  Closing this issue for now.
