### ISSUE TITLE
Create duc package for yum and zypper

### ISSUE THREAD

**Issue by AbhinavHegde97** [zevv/duc#320]
I was planning to use duc in production for my project and was wondering if it is feasible to create a package on yum and zypper for duc

so that i can install duc package using the 

sudo yum install duc

sudo zypper install duc

**Comment by cheese1** [comment]
you might want to try
http://www.nosuchhost.net/~cheese/fedora/packages/38/x86_64/duc.html

nb.: this is *NOT* official, just my packages for fedora and sometimes redhat

**Comment by l8gravely** [comment]
Thanks, if you have instructions for how you build that package, or even better, a patch which implements building the package using the existing makefile, that would be awesome.  

I've been thinking about setting up an openSuse text VM to play with building duc, but haven't done anything yet.  Any help is much appreciated.   

For now, this issue is closed.
