### ISSUE TITLE
Failure to index 15TB drive

### ISSUE THREAD

**Issue by asmartin** [zevv/duc#35]
Hello,

I am running duc on an NFS mountpoint of a 15TB filesystem on Ubuntu 12.04 server with the following options:
duc index /path/to/mount

After running for several hours, duc appears to be no longer indexing. If I strace the process, I see the following being printed over and over:

```
pread(3, "\260\0\0\t\0\264\0!\363Q\3\206\4\230\n9b37\205\227kL\34U\24\200g\226\n\224\1"..., 256, 198681088) = 256
pread(3, "\260\0\0\t\0\264\0!\363Q\3\206\4\230\n9b37\205\227kL\34U\24\200g\226\n\224\1"..., 256, 198681088) = 256
```

Also the duc database has not been modified for several hours, which also leads me to believe that it is no longer actively indexing.

Note that this filesystem does contain a large number of hardlinks. Is there any other information I can provide to help diagnose why duc appears to be stuck indexing?

Thanks!

**Comment by aiamuzz** [comment]
@zevv ... even i am facing a fatal error while creating index ...
```
$ duc index -p /home/
fatal error: out of memoryn 44.5K files and 9.5K directories
```
does the index DB file get stored in one single location or on the respective path/partition its used to index ?
FYI ... currently my `/home` does have more than 1 GB free ... of a total size of 109 GB `/home` partition ...

going by @asmartin 's proportions of 20GB database size while indexing a 15TB volume ... i'd say my 1 GB as against my 109GB partition/directory i am trying to index should be well withing limit ... don't you think ?

**Comment by l8gravely** [comment]
>>>>> "aiamuzz" == aiamuzz  ***@***.***> writes:

aiamuzz> @zevv ... even i am facing a fatal error while creating index ...
aiamuzz> $ duc index -p /home/
aiamuzz> fatal error: out of memoryn 44.5K files and 9.5K directories

This looks to be more of a RAM issue, not a disk space issue.  Can you
give us more info about your system?  Can you run 'top' in another
window and watch how the system handles the indexing?  

aiamuzz> does the index DB file get stored in one single location or
aiamuzz> on the respective path/partition its used to index ?  FYI
aiamuzz> ... currently my /home does have more than 1 GB free ... of a
aiamuzz> total size of 109 GB /home partition ...

The database gets stored where you tell it be put, either using the -d
<path> option, or setting the DUC_DATABASE environment variable.
Otherwise it defaults to ~/.duc.db

aiamuzz> going by @asmartin 's proportions of 20GB database size while
aiamuzz> indexing a 15TB volume ... i'd say my 1 GB as against my
aiamuzz> 109GB partition/directory i am trying to index should be well
aiamuzz> withing limit ... don't you think ?

It should be plenty of room.  But how many files do you have?  That's
another issue, so looking at the output of:

  df -i /home/

would be useful to know as well.  But in general, please give us more
information, and look in the /var/log/syslog and the output of 'dmesg'
to see what's going on at the system level.

Also, you might be limited in how much memory your process can take,
so check the output of 'ulimit -a' to see if you are hitting any
limits there.

John
