### ISSUE TITLE
drwx--x--x permissions cause further size analysis to fail

### ISSUE THREAD

**Issue by ech3** [zevv/duc#53]
I am running duc, and when I try and run it over a directory that has a sub-directory with the following permissions:
```
drwx--x--x
```

in a directory I do not have ownership for. I will get error messages like the following (changed a bit from original file names):

```
Writing to junk.duc
Skipping dir0: Permission denied
Error statting dir1: No such file or directory
Error statting dir2: No such file or directory
Error statting file1.cc: No such file or directory
....[Ed. Errors continue for various directories / files that were analyzed after the one with the bad permissions.]
```

When I generate the graph, it seems to not analyze any of the files after the directory with these permissions. I can't zip up an example due to file size / company policies, but could probably recreate a smaller scale version of this. If you need more complete instructions to reproduce the issue let me know, and I will try and come up with something more complete.

**Comment by l8gravely** [comment]
>>>>> "ech3" == ech3  <notifications@github.com> writes:

ech3> I am running duc, and when I try and run it over a directory
ech3> that has a sub-directory with the following permissions:
ech3> drwx--x--x

ech3> in a directory I do not have ownership for. I will get error
ech3> messages like the following (changed a bit from original file
ech3> names):

ech3> Writing to junk.duc
ech3> Skipping dir0: Permission denied
ech3> Error statting dir1: No such file or directory
ech3> Error statting dir2: No such file or directory
ech3> Error statting file1.cc: No such file or directory

ech3> ....[Ed. Errors continue for various directories / files that
ech3> were analyzed after the one with the bad permissions.]

ech3> When I generate the graph, it seems to not analyze any of the
ech3> files after the directory with these permissions. I can't zip up
ech3> an example due to file size / company policies, but could
ech3> probably recreate a smaller scale version of this. If you need
ech3> more complete instructions to reproduce the issue let me know,
ech3> and I will try and come up with something more complete.


Just to make it clear, you have directory called 'foo' with
permissions 'drwx--x--x' owned by someone else, and inside it you have
dir0, dir1 and dir2 which you CAN read?  

It would be helpful if you could setup a small test case, send the
output of 'ls -r

**Comment by l8gravely** [comment]
Dammit, I hit send too quickly.  Anyway, if you could send the output of:

  find dir -ls

and the screen shot of your duc command and the output, that would be helpful.  But it's really going to come down to needing to run duc as a user with the permissions to be able to descend into all directories and readdir() in them to pull out the info.  

My general solution is to run duc a root, either in a cronjob, or via sudo to generate the data.

**Comment by zevv** [comment]
Hi,

I'm able to repoduce, currently in the process of debugging. Thanks for
your report,


* On 2015-01-19 19:08:52 +0100, ech3 wrote:
 
> I am running duc, and when I try and run it over a directory that has a sub-directory with the following permissions:
> ```
> drwx--x--x
> ```
> 
> in a directory I do not have ownership for. I will get error messages like the following (changed a bit from original file names):
> 
> ```
> Writing to junk.duc
> Skipping dir0: Permission denied
> Error statting dir1: No such file or directory
> Error statting dir2: No such file or directory
> Error statting file1.cc: No such file or directory
> ....[Ed. Errors continue for various directories / files that were analyzed after the one with the bad permissions.]
> ```
> 
> When I generate the graph, it seems to not analyze any of the files after the directory with these permissions. I can't zip up an example due to file size / company policies, but could probably recreate a smaller scale version of this. If you need more complete instructions to reproduce the issue let me know, and I will try and come up with something more complete.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/issues/53

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by ech3** [comment]
I have updated to a build that included your fix and the problem is now resolved on my end as well. Thanks for the quick turn around time.
