### ISSUE TITLE
duc gui: extended information on mouse hovering

### ISSUE THREAD

**Issue by nonsns** [zevv/duc#68]
**feature request**

it would be useful to display extended information as a tooltip while hovering the mouse over a region, in particular:
* the folder name
* the folder total size
* the total number of files

this is already somehow possible (since, once you click over the same region, then you go to that folder; which means that the information is already fairly accessible). however, I had a look at the code and have no idea how this could be implemented in practice

PS.
I love the tool. this is a small suggestion to make it even more lovely

**Comment by zevv** [comment]
Indeed a nice to have. 

I've created an experimental branch which does this, but it needs some improvements still. The tooltip drawing is done from duc_draw_graph(), because here the proper info is available to find the name and size during rendering. An extra API function has been added to pass the current mouse pointer location to the duc graph context so it knows where to draw the tooltip.

**Comment by zevv** [comment]
Tooltip branch has just been merged to master. Info in the tooltip is limited to file/dir name and total size, this can be improved by giving more info if available.

Please give it a spin!

**Comment by nonsns** [comment]
:+1: 

Great, the info that is currently displayed (pathname + size)  is what matters the most. Adding information directly in the tooltip would probably make it unreadable (as if the size of the tooltip increase, it will also more likely overlap with some other static rendered text).

An option would be to add futher information in a "status bar"-like place -- but the downside is that it may be distracting to look at two different places. 

So I guess that the current tooltip is just fine to find "where are my bytes" :)
