### ISSUE TITLE
Configure options to build for ncurses and cairo/pango

### ISSUE THREAD

**Issue by NP-Hardass** [zevv/duc#78]
This will allow users who want your program in a non-gui environment to do so (assuming your code is capable of doing so)  This also would allow those that don't want console support to toggle that as well. 
I'd very much like to see this on gentoo so our users can select at build time what interfaces they'd like to have.

Thanks :)

**Comment by zevv** [comment]
So, what i need to add comes down to a few flags for configure:

--without-X11
--without-graphs
--without-ncurses

to be able to build only parts of duc, without forcing dependencies on X11, cairo, pango or ncurses.

Thanks for helping with the gentoo ebuild, I've added that to the repo as well.

**Comment by zevv** [comment]
@l8gravely: Yesterday I've been speaking with some people from the gentoo and debian community to discuss how get a package accepted for inclusion in the official repositories. Simple packages are greatly preffered, and I've been advised to drop the current setup with multiple shared libraries and just create a single binary.

This is fine with me; the current design with separate libraries was made because the original planning was to make multiple command line tools which would all link to libduc. At this time we have just one single 'duc' tool, so switching back is trivial. As long as we keep the libs and API strictly separated in the code we can always switch back once the need arises.

Any thoughts?

**Comment by zevv** [comment]
Fixed, this is now in release 1.0-rc1

**Comment by l8gravely** [comment]
zevv> @l8gravely: Yesterday I've been speaking with some people from
zevv> the gentoo and debian community to discuss how get a package
zevv> accepted for inclusion in the official repositories. Simple
zevv> packages are greatly preffered, and I've been advised to drop
zevv> the current setup with multiple shared libraries and just create
zevv> a single binary.

zevv> This is fine with me; the current design with separate libraries
zevv> was made because the original planning was to make multiple
zevv> command line tools which would all link to libduc. At this time
zevv> we have just one single 'duc' tool, so switching back is
zevv> trivial. As long as we keep the libs and API strictly separated
zevv> in the code we can always switch back once the need arises.

zevv> Any thoughts?

I have no problems with this method, in fact it will simplify things
quite a bit.  I'll see what I can do to make this change in a new
branch this week.  Basically, I'll just setup things to make a single
duc.a library which gets linked in, instead of duc.so.  Should be a
fairly simple change.

John

**Comment by l8gravely** [comment]
Guys,

I've got an initial couple of changes so that we don't build a shared
library any more, just a libduc.a to be linked in at compile time.
But it's still installing it.  I need to do some more work.

When I push this, it will be branch static-lib and I hopefully will
have it working more reliably.

I've looked at how you work around the missing ncurses lib and I'm not
wild about it, since it looks like you just stub out all the stuff in
cmd-ui.c, but not in duc/main.c so that the ui (or gui) commands
aren't even shown.  I need to test this more, but I think there are
more patches needed here.

Same issue with the cmd-gui stuff as well, but I think again that we
should just not compile that stuff at all, and update main.c to skip
those functions as well.  We should also group the X11, Cairo, Pango,
CairoPango lib checks all together, under one HAVE_DUC_GUI define
which we can use to compile out stuff properly.

John

**Comment by zevv** [comment]
* On 2015-04-27 22:22:01 +0200, John wrote:

> I've got an initial couple of changes so that we don't build a shared
> library any more, just a libduc.a to be linked in at compile time.
> But it's still installing it.  I need to do some more work.

I think the code in lib/ducgraph deserves to go in a separate (static) lib as
well. The current source directory layout already seperates those.
 
> I've looked at how you work around the missing ncurses lib and I'm not
> wild about it, since it looks like you just stub out all the stuff in
> cmd-ui.c, but not in duc/main.c so that the ui (or gui) commands
> aren't even shown. 

No need to stub that out: because the cmd structs are not resolved at link
time, the pointers in cmd_list[] end up being NULL; the code in main.c checks
for the NULL pointer and omits these commands during list iteration.

> Same issue with the cmd-gui stuff as well, but I think again that we
> should just not compile that stuff at all, 

We could try not to compile the source files for these commands, but I chose
the current solution because conditional inclusion of source files is not an
easy thing to do with automake. At this time all soures are fed through the
compiler, but some source files are effectively disabled because of the #ifdefs
enclosing them. (eg, ENABLE_GUI)

> We should also group the X11, Cairo, Pango, CairoPango lib checks all
> together, under one HAVE_DUC_GUI define which we can use to compile
> out stuff properly.

There's still duc-graph and duc-cgi (cairo/pango), even when there's no
duc-gui (X11), so these should kept separate, imho.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
>>>>> "zevv" == zevv  <notifications@github.com> writes:

zevv> * On 2015-04-27 22:22:01 +0200, John wrote:
>> I've got an initial couple of changes so that we don't build a shared
>> library any more, just a libduc.a to be linked in at compile time.
>> But it's still installing it. I need to do some more work.

zevv> I think the code in lib/ducgraph deserves to go in a separate
zevv> (static) lib as well. The current source directory layout
zevv> already seperates those.

Ok, I'll see about doing that too, but possibly down the time.  

>> I've looked at how you work around the missing ncurses lib and I'm not
>> wild about it, since it looks like you just stub out all the stuff in
>> cmd-ui.c, but not in duc/main.c so that the ui (or gui) commands
>> aren't even shown.

zevv> No need to stub that out: because the cmd structs are not
zevv> resolved at link time, the pointers in cmd_list[] end up being
zevv> NULL; the code in main.c checks for the NULL pointer and omits
zevv> these commands during list iteration.

Ok, thanks for the heads up, I ran into other work I needed to do last
night and didn't touch duc at all.  Maybe today if I get lucky...

>> Same issue with the cmd-gui stuff as well, but I think again that we
>> should just not compile that stuff at all,

zevv> We could try not to compile the source files for these commands,
zevv> but I chose the current solution because conditional inclusion
zevv> of source files is not an easy thing to do with automake. At
zevv> this time all soures are fed through the compiler, but some
zevv> source files are effectively disabled because of the #ifdefs
zevv> enclosing them. (eg, ENABLE_GUI)

Actually, it's not hard to do conditional includes.  I'll be doing
that as I pull out the pango/cairo stuff down the line.  Though it's
also not a big deal if we turn it into a library.  

Basically, it's not hard.   

>> We should also group the X11, Cairo, Pango, CairoPango lib checks all
>> together, under one HAVE_DUC_GUI define which we can use to compile
>> out stuff properly.

zevv> There's still duc-graph and duc-cgi (cairo/pango), even when
zevv> there's no duc-gui (X11), so these should kept separate, imho.

Hmm... so let's break this down a bit, and try to decide what the
--enable-<feature> / --disable-<feature> names should be, to make it
clear to the end users.  Hah!  

Esp considering that you were told that it's easier on packagers for
debian or other distros if we don't ship a libduc.so library.  

So right now we have:

tokyocabinet 	- required absolutely, no enable/disable.
ncurses		- required for cmd-ui, default enable if found.
cairo/pango	- required for cmd-gui, cmd-cgi, default enable if found
X11		- reuquired for cmd-gui, default enable if found


So maybe the obvious option is merely:  --enable-indexer-only   which
would just require the core tokyocabninet and build the indexing
version and nothing else.  Well, info would be there too, but that's
just the inverse of the indexer.  

How does that sound as a plan?  

And this brings up the idea should we have duc-<cmd> binaries (which
could be symlinks to a master duc binary?  Decisions... decisions...

John

**Comment by zevv** [comment]
* On 2015-04-28 16:45:00 +0200, John wrote:
 
> tokyocabinet     - required absolutely, no enable/disable.

Even more fun, since yesterday there's a --with-db-backend option where
the user can choose the backend. Currently it supports tokyocabinet,
leveldb and sqlite. (I had this code lying around from the time when I
was doing performance and db size tests. Tokyocabinet was a good choice
because of the size of the database, but leveldb is more robust and
faster)

> ncurses        - required for cmd-ui, default enable if found.
> cairo/pango    - required for cmd-gui, cmd-cgi, default enable if found
> X11            - reuquired for cmd-gui, default enable if found

From various sources I understood that it is frowned upon to build
conditionaly depending on library availability. It is considered good
practice to make things explicit by letting the user choose at
./configure time. For example, see:

https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies


> And this brings up the idea should we have duc-<cmd> binaries (which
> could be symlinks to a master duc binary? 

I don't really see any advantages for that, I'm quite happy with the
current setup with subcommands.

-- 
:wq
^X^Cy^K^X^C^C^C^C
