### ISSUE TITLE
RFE to display directory name and size when navigating cursor in cgi mode

### ISSUE THREAD

**Issue by stuartthebruce** [zevv/duc#89]
Instead of displaying pixel coordinates while navigating the cursor over a cgi mode graph I believe it would be more useful to display the directory name and size that would be shown if a user clicked on a given location.

This would make it easier to navigate large graphs where not all of the directories are initially rendered with name/size information since some are too small.

**Comment by zevv** [comment]
* On 2015-05-12 01:57:24 +0200, stuartthebruce wrote:
 
> Instead of displaying pixel coordinates while navigating the cursor
> over a cgi mode graph I believe it would be more useful to display the
> directory name and size that would be shown if a user clicked on a
> given location.
> 
> This would make it easier to navigate large graphs where not all of
> the directories are initially rendered with name/size information
> since some are too small.

The coordinates are a mere side effect of the implementation, which uses
image maps to find out where the user clicked on the image. The CGI does
not know anything about the paths in the image, because the next path is
only looked up by coordinates when the click is posted to the server.

I guess what you are really asking is some kind of tooltip to get info
about the graph section under the mouse cursor? This is technically
possible of course, but requires round-trips between browser and server
to query information while moving the mouse with something like
XMLHttpRequest.

I'm not really sure where I want to go with the CGI interface. My goal
is to keep Duc simple and small, but having more functionality in the
CGI would probably complicate things. In the past I received a number of
patches from users implementing tooltips, but they all come with a lot
of additional files like style sheets, javascript libraries, etc.

I'd be ok with a very simple implementation which is totally embedded
in the CGI, I'll see if I can fix up something one of these days.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
I've added a minimal tooltip implementation in a separate branch `cgi-tooltip`. The functionality can be enabled by setting the --tooltip option on the CGI, I'd rather not enable it by default since it will cause a fair amount of HTTP requests every time the mouse is moved.

Please give it a try, any feedback appreciated.

**Comment by stuartthebruce** [comment]
The basic idea looks good, however, the information displayed in the tooltip window is out of sync with the displayed graph once I click to drill down one level, and the "close this window" button is inaccessible (at least in my browser) since the tooltip window disappears as soon as I move the mouse. Here is an initial top-level image where the tooltip window has correct information,

![pastedgraphic-8](https://cloud.githubusercontent.com/assets/12385914/7598687/1a13b78a-f8b1-11e4-94fd-059f6a744771.png)

and here is an image where it shows the wrong information. In particular, it appears to be resolving the pixel coordinates from the previous parent graph that was displayed before I selected a particular directory to zoom in on,

![pastedgraphic-9](https://cloud.githubusercontent.com/assets/12385914/7598720/3f247a78-f8b1-11e4-97a1-8f7bf7902de5.png)

**Comment by zevv** [comment]
* On 2015-05-12 23:15:17 +0200, stuartthebruce wrote:
 
> The basic idea looks good, however, the information displayed in the
> tooltip window is out of sync with the displayed graph once I click to
> drill down one level, and the "close this window" button is
> inaccessible (at least in my browser) since the tooltip window
> disappears as soon as I move the mouse. 

Yes, you're absolutely right. I just fixed this in the branch, please
pull and retry.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
* On 2015-05-12 23:15:17 +0200, stuartthebruce wrote:
 
> the "close this window" button is inaccessible (at least in my
> browser) since the tooltip window disappears as soon as I move the
> mouse. 

That's funny: the 'close this window' button comes out of the blue, it
is certainly not generated by Duc. I guess your browser is smarter then
me and thinks the tooltip is a popup window serving ads or something
like that, and decides to insert a button into the <div> so the user can
hide it.

What browser on what OS are you using?

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by stuartthebruce** [comment]
> On May 12, 2015, at 2:46 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-12 23:15:17 +0200, stuartthebruce wrote:
> 
> > The basic idea looks good, however, the information displayed in the
> > tooltip window is out of sync with the displayed graph once I click to
> > drill down one level, and the "close this window" button is
> > inaccessible (at least in my browser) since the tooltip window
> > disappears as soon as I move the mouse. 
> 
> Yes, you're absolutely right. I just fixed this in the branch, please
> pull and retry.

That fixed it.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by stuartthebruce** [comment]
On May 12, 2015, at 2:51 PM, Ico Doornekamp <notifications@github.com> wrote:
> 
> * On 2015-05-12 23:15:17 +0200, stuartthebruce wrote:
> 
> > the "close this window" button is inaccessible (at least in my
> > browser) since the tooltip window disappears as soon as I move the
> > mouse. 
> 
> That's funny: the 'close this window' button comes out of the blue, it
> is certainly not generated by Duc. I guess your browser is smarter then
> me and thinks the tooltip is a popup window serving ads or something
> like that, and decides to insert a button into the <div> so the user can
> hide it.
> 
> What browser on what OS are you using?

Doh…that comes from my cgi script that calls “duc cgi” but then appends the
following at the bottom of the page,

<center><input type=“button” value=“Close this window" onclick="self.close()">

That should be straightforward to cleanup.

Thanks.

--
Stuart Anderson  anderson@ligo.caltech.edu
http://www.ligo.caltech.edu/~anderson

**Comment by zevv** [comment]
Merged tooltip to trunk, closing issue
